# NOTE: This repo contains only the documentation for the private BoltsOps repo code.
# Original file: https://github.com/boltops-pro/demo-apps/blob/main/java/spring/frontend-maven/.kubes/resources/web/deployment/dev.yaml
# The docs are publish so they are available for interested subscribers.
# For access to the source code, you can become a BoltOps subscriber.
# See: https://learn.boltops.com
